default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 1234
  host: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development
test:
  <<: *default
  database: app_test

production:
  url:
