source 'https://rubygems.org'
ruby '2.5.0'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end
gem 'rails', '~> 5.1.4'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.7'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
group :development, :test do
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

### END RAILS ###

group :test do
  gem 'rack_session_access'
  gem 'mocha'
  gem 'shoulda-matchers'
  gem 'database_cleaner'
end

group :development do
  gem 'guard-rspec'
  gem 'spring-commands-rspec'
  gem 'capistrano'
  gem 'capistrano-rails'
  gem 'capistrano-bundler'
  gem 'capistrano3-puma'
  gem 'capistrano-rvm'
end

group :test, :development do
  gem 'poltergeist'
  gem 'rspec-rails'
  gem 'factory_bot_rails'
end

### Frontend ###

gem 'materialize-sass'
gem 'font-awesome-rails'
gem 'jquery-rails'
gem 'draper'

### Authentication ###
gem 'bcrypt', '~> 3.1.7'